"""
Blog 2: Format-Aware Parser Orchestrator

Main orchestrator that reads routing table from Blog 1 and routes documents
to appropriate parsers based on their format and routing tags.
"""

import logging
from pathlib import Path
from typing import Dict, List, Optional, Union
from dataclasses import dataclass, asdict
import json
from tqdm import tqdm

from src.audit import CorpusAuditor
from src.utils.json_store import JSONStore
from src.utils.logger import get_logger
from src.utils.tracker import PerformanceTracker
from src.utils.config import config

from .pdf_parser import parse_pdf_text
from .pdf_ocr_parser import parse_pdf_ocr
from .html_parser import parse_html
from .json_parser import parse_json
from .csv_parser import parse_csv
from .simple_parsers import parse_plaintext, parse_markdown, parse_python

logger = get_logger(__name__)


@dataclass
class ParsedDocument:
    """Container for parsed document"""
    doc_id: str
    format_type: str
    routing_tag: str
    parser_used: str
    status: str  # success, partial, failed
    error_message: Optional[str]
    extracted_text: str
    metadata: Dict
    document_objects: Dict  # Format-specific parsed object


class FormatAwareParser:
    """
    Main parser orchestrator.
    
    Reads routing table from Blog 1 and routes documents to appropriate parsers.
    """

    def __init__(self, config_dict: Optional[Dict] = None):
        """Initialize parser"""
        self.config = config_dict or {}
        self.json_store = JSONStore()
        self.tracker = PerformanceTracker()
        
        # Load routing table from Blog 1
        self.routing_table = self._load_routing_table()

    def _load_routing_table(self) -> Dict:
        """Load routing table generated by Blog 1"""
        try:
            routing_file = Path(config.get("metadata_dir")) / "routing_table.json"
            if routing_file.exists():
                return self.json_store.load_single(str(routing_file))
            else:
                logger.warning("Routing table not found. Running Blog 1 first...")
                auditor = CorpusAuditor()
                auditor.audit_corpus()
                return self.json_store.load_single(str(routing_file))
        except Exception as e:
            logger.error(f"Error loading routing table: {e}")
            return {}

    def parse_pdf_document(self, doc_path: Path, doc_id: str, routing_tag: str) -> ParsedDocument:
        """Parse PDF based on routing tag"""
        try:
            if "scanned" in routing_tag:
                # Scanned PDF - use OCR
                result = parse_pdf_ocr(doc_path, doc_id)
                extracted_text = result.total_text
                parser_used = "pdf_ocr"
                metadata = {
                    "average_confidence": result.average_confidence,
                    "average_quality": result.average_image_quality,
                    "languages": result.languages_detected,
                    "page_results": result.ocr_results
                }
            else:
                # Text PDF - use standard text extraction
                result = parse_pdf_text(doc_path, doc_id)
                extracted_text = result.total_text
                parser_used = "pdf_text"
                metadata = {
                    "extraction_quality": result.extraction_quality,
                    "column_count": result.column_count,
                    "has_headers_footers": result.has_headers_footers,
                    "reading_order": result.reading_order,
                    "total_pages": result.total_pages
                }
            
            return ParsedDocument(
                doc_id=doc_id,
                format_type="pdf",
                routing_tag=routing_tag,
                parser_used=parser_used,
                status="success",
                error_message=None,
                extracted_text=extracted_text,
                metadata=metadata,
                document_objects={"parsed": result}
            )
        
        except Exception as e:
            logger.error(f"Error parsing PDF {doc_id}: {e}")
            return ParsedDocument(
                doc_id=doc_id,
                format_type="pdf",
                routing_tag=routing_tag,
                parser_used="pdf_error",
                status="failed",
                error_message=str(e),
                extracted_text="",
                metadata={},
                document_objects={}
            )

    def parse_html_document(self, doc_path: Path, doc_id: str, routing_tag: str) -> ParsedDocument:
        """Parse HTML document"""
        try:
            result = parse_html(doc_path, doc_id)
            
            return ParsedDocument(
                doc_id=doc_id,
                format_type="html",
                routing_tag=routing_tag,
                parser_used="html",
                status="success",
                error_message=None,
                extracted_text=result.main_content,
                metadata={
                    "title": result.title,
                    "extraction_method": result.extraction_method,
                    "content_quality": result.content_quality,
                    "language": result.language,
                    "charset": result.charset,
                    "structure": result.structure
                },
                document_objects={"parsed": result}
            )
        
        except Exception as e:
            logger.error(f"Error parsing HTML {doc_id}: {e}")
            return ParsedDocument(
                doc_id=doc_id,
                format_type="html",
                routing_tag=routing_tag,
                parser_used="html_error",
                status="failed",
                error_message=str(e),
                extracted_text="",
                metadata={},
                document_objects={}
            )

    def parse_json_document(self, doc_path: Path, doc_id: str, routing_tag: str) -> ParsedDocument:
        """Parse JSON document"""
        try:
            result = parse_json(doc_path, doc_id)
            
            return ParsedDocument(
                doc_id=doc_id,
                format_type="json",
                routing_tag=routing_tag,
                parser_used="json",
                status="success",
                error_message=None,
                extracted_text=result.flattened_text,
                metadata={
                    "schema_depth": result.schema_depth,
                    "key_count": result.key_count,
                    "has_arrays": result.has_arrays,
                    "has_nested_objects": result.has_nested_objects,
                    "parsing_quality": result.parsing_quality
                },
                document_objects={"parsed": result}
            )
        
        except Exception as e:
            logger.error(f"Error parsing JSON {doc_id}: {e}")
            return ParsedDocument(
                doc_id=doc_id,
                format_type="json",
                routing_tag=routing_tag,
                parser_used="json_error",
                status="failed",
                error_message=str(e),
                extracted_text="",
                metadata={},
                document_objects={}
            )

    def parse_csv_document(self, doc_path: Path, doc_id: str, routing_tag: str) -> ParsedDocument:
        """Parse CSV document"""
        try:
            result = parse_csv(doc_path, doc_id)
            
            return ParsedDocument(
                doc_id=doc_id,
                format_type="csv",
                routing_tag=routing_tag,
                parser_used="csv",
                status="success",
                error_message=None,
                extracted_text=result.data_preview,
                metadata={
                    "headers": result.headers,
                    "rows": result.rows,
                    "columns": result.columns,
                    "delimiter": result.delimiter,
                    "has_headers": result.has_headers,
                    "parsing_quality": result.parsing_quality
                },
                document_objects={"parsed": result}
            )
        
        except Exception as e:
            logger.error(f"Error parsing CSV {doc_id}: {e}")
            return ParsedDocument(
                doc_id=doc_id,
                format_type="csv",
                routing_tag=routing_tag,
                parser_used="csv_error",
                status="failed",
                error_message=str(e),
                extracted_text="",
                metadata={},
                document_objects={}
            )

    def parse_text_document(self, doc_path: Path, doc_id: str, routing_tag: str) -> ParsedDocument:
        """Parse plain text document"""
        try:
            result = parse_plaintext(doc_path, doc_id)
            
            return ParsedDocument(
                doc_id=doc_id,
                format_type="txt",
                routing_tag=routing_tag,
                parser_used="plaintext",
                status="success",
                error_message=None,
                extracted_text=result.content,
                metadata={
                    "line_count": result.line_count,
                    "word_count": result.word_count,
                    "avg_line_length": result.avg_line_length,
                    "parsing_quality": result.parsing_quality
                },
                document_objects={"parsed": result}
            )
        
        except Exception as e:
            logger.error(f"Error parsing text {doc_id}: {e}")
            return ParsedDocument(
                doc_id=doc_id,
                format_type="txt",
                routing_tag=routing_tag,
                parser_used="plaintext_error",
                status="failed",
                error_message=str(e),
                extracted_text="",
                metadata={},
                document_objects={}
            )

    def parse_markdown_document(self, doc_path: Path, doc_id: str, routing_tag: str) -> ParsedDocument:
        """Parse Markdown document"""
        try:
            result = parse_markdown(doc_path, doc_id)
            
            return ParsedDocument(
                doc_id=doc_id,
                format_type="md",
                routing_tag=routing_tag,
                parser_used="markdown",
                status="success",
                error_message=None,
                extracted_text=result.content,
                metadata={
                    "headings": result.headings,
                    "code_blocks": result.code_blocks,
                    "links": result.links,
                    "tables": result.tables,
                    "line_count": result.line_count,
                    "parsing_quality": result.parsing_quality
                },
                document_objects={"parsed": result}
            )
        
        except Exception as e:
            logger.error(f"Error parsing markdown {doc_id}: {e}")
            return ParsedDocument(
                doc_id=doc_id,
                format_type="md",
                routing_tag=routing_tag,
                parser_used="markdown_error",
                status="failed",
                error_message=str(e),
                extracted_text="",
                metadata={},
                document_objects={}
            )

    def parse_code_document(self, doc_path: Path, doc_id: str, routing_tag: str) -> ParsedDocument:
        """Parse Python code document"""
        try:
            result = parse_python(doc_path, doc_id)
            
            return ParsedDocument(
                doc_id=doc_id,
                format_type="py",
                routing_tag=routing_tag,
                parser_used="python",
                status="success",
                error_message=None,
                extracted_text=result.content,
                metadata={
                    "functions": result.functions,
                    "classes": result.classes,
                    "imports": result.imports,
                    "docstring": result.docstring,
                    "line_count": result.line_count,
                    "parsing_quality": result.parsing_quality
                },
                document_objects={"parsed": result}
            )
        
        except Exception as e:
            logger.error(f"Error parsing Python code {doc_id}: {e}")
            return ParsedDocument(
                doc_id=doc_id,
                format_type="py",
                routing_tag=routing_tag,
                parser_used="python_error",
                status="failed",
                error_message=str(e),
                extracted_text="",
                metadata={},
                document_objects={}
            )

    def parse_document(self, doc_path: Path, doc_id: str) -> Optional[ParsedDocument]:
        """
        Route and parse single document based on format and routing tag.
        
        Args:
            doc_path: Path to document
            doc_id: Document ID
            
        Returns:
            ParsedDocument or None if document not found
        """
        # Get routing info from routing table
        if doc_id not in self.routing_table:
            logger.warning(f"Document {doc_id} not in routing table")
            return None
        
        routing_info = self.routing_table[doc_id]
        format_type = routing_info.get("format_type", "unknown")
        routing_tag = routing_info.get("routing_tag", "unknown")
        
        # Route to appropriate parser
        if format_type == "pdf":
            return self.parse_pdf_document(doc_path, doc_id, routing_tag)
        elif format_type == "html":
            return self.parse_html_document(doc_path, doc_id, routing_tag)
        elif format_type == "json":
            return self.parse_json_document(doc_path, doc_id, routing_tag)
        elif format_type == "csv":
            return self.parse_csv_document(doc_path, doc_id, routing_tag)
        elif format_type == "txt":
            return self.parse_text_document(doc_path, doc_id, routing_tag)
        elif format_type == "md":
            return self.parse_markdown_document(doc_path, doc_id, routing_tag)
        elif format_type == "py":
            return self.parse_code_document(doc_path, doc_id, routing_tag)
        else:
            logger.warning(f"Unknown format type: {format_type}")
            return None

    def parse_corpus(self) -> Dict:
        """
        Parse entire corpus using routing table from Blog 1.
        
        Returns:
            Summary dictionary with statistics
        """
        logger.info("Starting Document Parsing (Blog 2)...")
        
        # Get raw corpus directory
        corpus_dir = Path(config.get("raw_corpus_dir"))
        
        # Discover all documents
        doc_paths = {}
        for doc_id, routing_info in self.routing_table.items():
            source_path = Path(routing_info["source_path"])
            if source_path.exists():
                doc_paths[doc_id] = source_path
        
        logger.info(f"Discovered {len(doc_paths)} documents to parse")
        
        # Parse all documents
        parsed_docs = []
        stats = {
            "total": len(doc_paths),
            "success": 0,
            "failed": 0,
            "by_format": {},
            "by_status": {"success": 0, "partial": 0, "failed": 0}
        }
        
        with self.tracker.track("parse_corpus"):
            for doc_id, doc_path in tqdm(doc_paths.items(), desc="Parsing documents"):
                parsed = self.parse_document(doc_path, doc_id)
                
                if parsed:
                    parsed_docs.append(parsed)
                    
                    # Update statistics
                    format_type = parsed.format_type
                    if format_type not in stats["by_format"]:
                        stats["by_format"][format_type] = {"success": 0, "failed": 0}
                    
                    if parsed.status == "success":
                        stats["success"] += 1
                        stats["by_format"][format_type]["success"] += 1
                        stats["by_status"]["success"] += 1
                    else:
                        stats["failed"] += 1
                        stats["by_format"][format_type]["failed"] += 1
                        stats["by_status"]["failed"] += 1
        
        # Save results
        self._save_results(parsed_docs, stats)
        
        logger.info(f"Parsing complete: {stats['success']} success, {stats['failed']} failed")
        
        return stats

    def _save_results(self, parsed_docs: List[ParsedDocument], stats: Dict):
        """
        Save parsed documents to storage.
        
        Args:
            parsed_docs: List of parsed documents
            stats: Statistics dictionary
        """
        # Create output directory
        output_dir = Path(config.get("processed_dir")) / "parsed_documents"
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Save parsed results (excluding large objects)
        results_data = []
        for doc in parsed_docs:
            doc_dict = asdict(doc)
            # Remove large object references
            doc_dict["document_objects"] = {"status": doc.status}
            results_data.append(doc_dict)
        
        results_file = output_dir / "parsed_results.json"
        self.json_store.save_list(results_data, str(results_file))
        logger.info(f"Saved parsed results to {results_file}")
        
        # Save statistics
        stats_file = output_dir / "parsing_stats.json"
        self.json_store.save_single(stats, str(stats_file))
        logger.info(f"Saved statistics to {stats_file}")


def run_parsing(sample_size: Optional[int] = None) -> Dict:
    """
    Run Blog 2 parsing on corpus.
    
    Args:
        sample_size: Optional limit for sample processing
        
    Returns:
        Summary dictionary
    """
    parser = FormatAwareParser()
    return parser.parse_corpus()
